feat(options): add support for globally allowing direct imports
bayesimpact/pylint_import_modules pull request #7
Opened 2019-08-05 23:42 UTC by TheKevJames

This changeset enables support for allowing any direct imports for a
given package with: `--allowed-direct-imports="typing.*"`.

This helps us support, eg. the Google Style Guide, where the `typing`
module is not meant to be effected by the "only import modules" rule.
[Source](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#22-imports).

For best results, this should be merged after #6, though there's no
explicit dependency.

---

`_parse_config` could be kept as a `List[Tuple[str, str]]` instead of a
`Dict[str, Set[str]]` if you prefer -- switching the format made parsing
easier but the changeset could easily be refactored to avoid the need.

This changeset marks `--allowed-direct-imports="typing.*,..."` as allowing
any direct imports from the `typing` package, but an alternative would
be to instead allow `--allowed-direct-imports="typing,..."`. I'm ambivalent
on the API here -- if you'd prefer the latter (or any other format), I'd be
happy to switch this around.

2019-08-06 12:21 UTC, zozoens31 requested changes
Thanks a lot for contributing to this package!

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/pylint_import_modules/7#-:-Llas4ZXC_9ruy0R2Jz4:b-kod5bd)* status: Missing an assignee or a reviewer, Unresolved discussions (pylint_import_modules/__init__.py:r1 line 18)

___
*[pylint_import_modules/__init__.py, line 18 at r1](https://reviewable.io/reviews/bayesimpact/pylint_import_modules/7#-LlarF2cBAlehHueFWWG:-LlarF2cBAlehHueFWWH:bdbex2q) ([raw file](https://github.com/bayesimpact/pylint_import_modules/blob/b39fa40a5f8ed3e685ba77c4afa77f8fea22c389/pylint_import_modules/__init__.py#L18)):*
> ```Python
> def _parse_config(config: str) -> Dict[str, Set[str]]:
>     if not config:
>         return {}
> ```

you could already return a defaultdict here, to avoid using `get` on lines 84 and 121
___
*[pylint_import_modules/__init__.py, line 85 at r1](https://reviewable.io/reviews/bayesimpact/pylint_import_modules/7#-Llas-0g7RUliTFSqThY:-Llas-0g7RUliTFSqThZ:b18vwbh) ([raw file](https://github.com/bayesimpact/pylint_import_modules/blob/b39fa40a5f8ed3e685ba77c4afa77f8fea22c389/pylint_import_modules/__init__.py#L85)):*
> ```Python
>         module_name = self._imports_to_check[name]
>         exceptions = self.exceptions.get(module_name, set())
>         if exceptions.intersection({node.attrname, '*'}):
> ```

please rather use`exceptions & {...}`. Same below


<!-- Sent from Reviewable.io -->

2019-08-06 12:29 UTC, zozoens31 reviewed
The `--allowed-direct-imports="typing,..."` would be ambiguous for submodules: Given `--allowed-direct-imports=name.subname`, would it mean that we can import the value (ie class or function) `subname` directly, or that we can import all members from the `name.subname` module directly? Granted, the ambiguity would be resolved in code, since astroid knows whether `name.subname` is a module or a value, but it still lacks clarity upon reading.

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/pylint_import_modules/7#-:-Llat8e4CRuEO2se9Aif:b13rvbv)* status: Missing an assignee or a reviewer, Unresolved discussions (pylint_import_modules/__init__.py:r1 line 18)



<!-- Sent from Reviewable.io -->

2019-08-06 17:21 UTC, TheKevJames commented
Updated for PR comments. Good call on the argument ambiguity; happy with my choice of `foo.*` then, or should we consider other options?

2019-08-07 09:06 UTC, zozoens31 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> `foo.*` is OK

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/pylint_import_modules/7#-:-LlfJxhx1xgy8gdlvlH-:b45j9b5)* status: Missing an assignee or a reviewer, Unresolved discussions (pylint_import_modules/__init__.py:r1 line 18)



<!-- Sent from Reviewable.io -->

2019-08-07 09:08 UTC, zozoens31 reviewed
+@zozoens31 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/pylint_import_modules/7#-:-LlfKVzk9J1HYpA-6UL8:b-gi25ac)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-07 09:10 UTC, merged